### ISSUE TITLE
output score is -1

### ISSUE THREAD

**Issue by ShirleyLiu-BCH** [lganel/SVScore#7]
Dear Author, 

thanks for the contribution on annotation of SVs, however I have exprericed a difficulty. 
when I run the test dataset with following command:
`./svscore.pl -c whole_genome_SNVs.tsv.gz -e refGene.exons.bed.gz -f refGene.introns.bed.gz -i tests/stresstest.vcf -o sum -v span`
The annotation results are all -1. For example,
'SVSCORESUM=-1;SVSCORESUM_LEFT=-1;SVSCORESUM_RIGHT=-1 '
Could you help?

Shirley

**Comment by lganel** [comment]
Hi Shirley,

The first thing I notice is that `-v` should not take an argument. What happens if you remove `span` from the command you listed? There is no way to show only the SPAN scores, but if you run SVScore with `-v`, the SPAN scores will be retained and you can extract them with `bcftools` or similar.

Also, have you tried running the stress test using the testing script provided? That is, `sh tests/test.sh path/to/whole_genome_SNVs.tsv.gz`

Best,

Liron

**Comment by lganel** [comment]
I'm closing this issue since I haven't heard from you. Please feel free to reach out again if you have any other questions.

**Comment by gn5** [comment]
Hi,
May I reopen this issue? I also get all `-1` scores in the output vcf.  
I have tried running the tests in `tests/test.sh` . The last 2 pass (I think) but the first one fails with a `Segmentation fault`:

```
Singularity>  $svscoredir/generateannotations.pl -c 1 -a 2 -b 3 -t 4 -s 5 -e 6 -f 7  -o $testdir $testdir/dummyannotations.bed 
# output bed `dummyannotations.exons.bed` and `dummyannotations.introns.bed` look ok, but then:

Singularity> $svscoredir/svscore.pl -f $testdir/dummyannotations.introns.bed -e $testdir/dummyannotations.exons.bed -o max,sum,top2,top2weighted,top3weighted,top4weighted,mean,meanweighted -dvc $testdir/dummyCADD.tsv.gz -i $testdir/stresstest.vcf > $testdir/stresstest.svscore.test.vcf

Writing config file
Preparing preprocessing command
Preprocessing command:
awk '$0~"^#" {print $0; next } { print $0 | "sort -k1,1V -k2,2n" }' /lustre/scratch119/humgen/projects/cnv_15x/svtools/results/svscore/gn5/tests/stresstest.vcf | bgzip -c > svscoretmp/stresstest1633958377.399.sort.vcf.gz; vcfanno -ends conf.toml svscoretmp/stresstest1633958377.399.sort.vcf.gz | perl /lustre/scratch119/realdata/mdt2/projects/cnv_15x/svtools/results/svscore/gn5/reorderheader.pl stdin /lustre/scratch119/humgen/projects/cnv_15x/svtools/results/svscore/gn5/tests/stresstest.vcf | svtools vcftobedpe > svscoretmp/stresstest1633958377.399.preprocess.bedpe

=============================================
vcfanno version 0.0.11-beta [built with devel +5ec87ba Thu Apr 28 15:36:34 2016 +0000]

see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:111: found 3 sources from 2 files
vcfanno.go:208: annotated 21 variants in 0.00 seconds (6639.0 / second)
Reading transcript list
Entering loop
Segmentation fault (core dumped)

```

This is using 
```
vcfanno version 0.0.11-beta [built with devel +5ec87ba Thu Apr 28 15:36:34 2016 +0000]
SVScore version 0.6
svtools 0.5.1
bgzip (htslib) 1.13
perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi
```
Running from a container I prepared:
https://github.com/wtsi-hgi/svscore_container/blob/main/Dockerfile
https://hub.docker.com/repository/docker/wtsihgi/svscore 

Do you know what I could try to get rid of this error and -1 scores?
Thank you,

Guillaume

**Comment by lganel** [comment]
Hi Guillaume,

Please open a separate issue. Getting scores of -1 is a somewhat general error, so your problem is probably separate from that in this issue.

Thanks,

Liron
