### ISSUE TITLE
test segmentation fault and -1 scores

### ISSUE THREAD

**Issue by gn5** [lganel/SVScore#8]
Hi,
I am getting all `-1` scores in the output vcf. To check if the software is installed correctly, I have then tried running the tests in `tests/test.sh` . The last one passes (I think) but the first one fails with a Segmentation fault:

```
Singularity>  $svscoredir/generateannotations.pl -c 1 -a 2 -b 3 -t 4 -s 5 -e 6 -f 7  -o $testdir $testdir/dummyannotations.bed 
# output bed `dummyannotations.exons.bed` and `dummyannotations.introns.bed` look ok, but then:

Singularity> $svscoredir/svscore.pl -f $testdir/dummyannotations.introns.bed -e $testdir/dummyannotations.exons.bed -o max,sum,top2,top2weighted,top3weighted,top4weighted,mean,meanweighted -dvc $testdir/dummyCADD.tsv.gz -i $testdir/stresstest.vcf > $testdir/stresstest.svscore.test.vcf

Writing config file
Preparing preprocessing command
Preprocessing command:
awk '$0~"^#" {print $0; next } { print $0 | "sort -k1,1V -k2,2n" }' /lustre/scratch119/humgen/projects/cnv_15x/svtools/results/svscore/gn5/tests/stresstest.vcf | bgzip -c > svscoretmp/stresstest1633958377.399.sort.vcf.gz; vcfanno -ends conf.toml svscoretmp/stresstest1633958377.399.sort.vcf.gz | perl /lustre/scratch119/realdata/mdt2/projects/cnv_15x/svtools/results/svscore/gn5/reorderheader.pl stdin /lustre/scratch119/humgen/projects/cnv_15x/svtools/results/svscore/gn5/tests/stresstest.vcf | svtools vcftobedpe > svscoretmp/stresstest1633958377.399.preprocess.bedpe

=============================================
vcfanno version 0.0.11-beta [built with devel +5ec87ba Thu Apr 28 15:36:34 2016 +0000]

see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:111: found 3 sources from 2 files
vcfanno.go:208: annotated 21 variants in 0.00 seconds (6639.0 / second)
Reading transcript list
Entering loop
Segmentation fault (core dumped)
``` 

This is using
```
vcfanno version 0.0.11-beta [built with devel +5ec87ba Thu Apr 28 15:36:34 2016 +0000]
SVScore version 0.6
svtools 0.5.1
bgzip (htslib) 1.13
perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi
```

Running from a container I prepared:
https://github.com/wtsi-hgi/svscore_container/blob/main/Dockerfile
https://hub.docker.com/repository/docker/wtsihgi/svscore

Do you know what I could try to get rid of this error and -1 scores?
Thank you,

Guillaume

**Comment by lganel** [comment]
Hi Guillaume,

I'm on it. I was able to reproduce your error by using your Docker image. I'll let you know when I find the cause.

Thanks!

Liron

**Comment by lganel** [comment]
Hi Guillaume,
The offending line seems to be https://github.com/lganel/SVScore/blob/master/svscore.pl#L370. It's unclear to me why this would cause a segfault, as this is a legitimate way of sorting an array in Perl. However, sorting in this way didn't cause an error in a separate test script in your Docker image. I'm not sure what's going on yet, but I'll keep working on it.

Liron

**Comment by lganel** [comment]
Hi @gn5,

Thanks for your patience.

This is a perl versioning issue. I was able to run the code inside a container made from your Docker image by doing the following (as root, i.e. including `-u root` in the Docker command):
```
apt-get update
apt-get -y upgrade # This should update your /usr/bin/perl
/usr/bin/cpan -fi List::MoreUtils Math::Round # Must agree for CPAN to automatically configure itself
svscoredir=/opt/conda/bin
testdir=/opt/conda/bin/tests
$svscoredir/generateannotations.pl -c 1 -a 2 -b 3 -t 4 -s 5 -e 6 -f 7  -o $testdir $testdir/dummyannotations.bed
$svscoredir/svscore.pl -f $testdir/dummyannotations.introns.bed -e $testdir/dummyannotations.exons.bed -o max,sum,top2,top2weighted,top3weighted,top4weighted,mean,meanweighted -dvc $testdir/dummyCADD.tsv.gz -i $testdir/stresstest.vcf > $testdir/stresstest.svscore.test.vcf
```

The last two commands are the same ones you posted above.

A word of warning: your Dockerfile installs Perl in `/opt/conda/bin`, but by default, SVScore will use the Perl in `/usr/bin/perl` (hence the need to specify `/usr/bin/cpan` above so that modules are found by the right perl). I suspect this may be the cause of your problem.

I hope this helps.

Liron

**Comment by gn5** [comment]
Hi Liron,

thanks for the help.
I think I've managed to build a docker container that passes the tests, indeed using a more recent perl version.
cf. `docker pull wtsihgi/svscore:2.0.0` (built from this [Dockerfile](https://github.com/wtsi-hgi/svscore_container/blob/main/Dockerfile)).

I ran the test inside the Dockerfile, and also after pulling the container with singularity (should work with docker too):
```
singularity pull docker://wtsihgi/svscore:2.0.0
singularity shell --containall svscore_2.0.0.sif

Singularity> mkdir tests && cp -r $testdir/* tests/ 
Singularity> export testdir=$PWD/tests
Singularity> generateannotations.pl -c 1 -a 2 -b 3 -t 4 -s 5 -e 6 -f 7 -o $testdir $testdir/dummyannotations.bed
Singularity> svscore.pl -f $testdir/dummyannotations.introns.bed -e $testdir/dummyannotations.exons.bed -o max,sum,top2,top2weighted,top3weighted,top4weighted,mean,meanweighted -dvc $testdir/dummyCADD.tsv.gz -i $testdir/stresstest.vcf > $testdir/stresstest.svscore.test.vcf
```

**Comment by lganel** [comment]
Glad to hear you've gotten the tests working! Are you comfortable with me closing this issue, then?

**Comment by gn5** [comment]
yes please close it.
